version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456789Vl@
      POSTGRES_DB: chaozao_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: